# Generated by Django 4.0.1 on 2022-01-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
    ]
